import { RootCommonState } from '../store';
import { tokenBalanceSlice } from 'packages/types/tokenBalance/slice';
import { tokenManagementSlice } from 'packages/types/store-ca/tokenManagement/slice';
import { recentSlice, RecentStateType } from 'packages/types/store-ca/recent/slice';

import { TokenState } from './token';
import { TokenBalanceState } from './tokenBalance';
import { assetsSlice, AssetsStateType } from 'packages/types/store-ca/assets/slice';
import { activitySlice } from 'packages/types/store-ca/activity/slice';
import { walletSlice } from 'packages/types/store-ca/wallet/slice';
import { WalletState } from 'packages/types/store-ca/wallet/type';
import { GuardiansState } from 'packages/types/store-ca/guardians/type';
import { guardiansSlice } from 'packages/types/store-ca/guardians/slice';
import { contactSlice, ContactState } from 'packages/types/store-ca/contact/slice';
import { ActivityStateType } from 'packages/types/store-ca/activity/type';
import { discoverSlice } from 'packages/types/store-ca/discover/slice';
import { IDiscoverStateType } from 'packages/types/store-ca/discover/type';

import { paymentSlice } from 'packages/types/store-ca/payment/slice';
import { PaymentStateType } from 'packages/types/store-ca/payment/type';
import { switchSlice, SwitchStateTypes } from 'packages/types/store-ca/switch/slice';
import { miscSlice } from 'packages/types/store-ca/misc/slice';
import { MiscState } from 'packages/types/store-ca/misc/types';
import { dappSlice } from 'packages/types/store-ca/dapp/slice';
import { IDappStoreState } from 'packages/types/store-ca/dapp/type';
import { cmsSlice } from 'packages/types/store-ca/cms/slice';
import { CMSState } from 'packages/types/store-ca/cms/types';
import txFeeSlice from 'packages/types/store-ca/txFee/slice';
import { TxFeeType } from 'packages/types/store-ca/txFee/type';
import imSlice from 'packages/types/store-ca/im/slice';
import { IMStateType } from 'packages/types/store-ca/im/type';

export type CACommonState = RootCommonState & {
  [tokenManagementSlice.name]: TokenState;
  [tokenBalanceSlice.name]: TokenBalanceState;
  [recentSlice.name]: RecentStateType;
  [assetsSlice.name]: AssetsStateType;
  [activitySlice.name]: ActivityStateType;
  [walletSlice.name]: WalletState;
  [contactSlice.name]: ContactState;
  [guardiansSlice.name]: GuardiansState;
  [discoverSlice.name]: IDiscoverStateType;
  [paymentSlice.name]: PaymentStateType;
  [switchSlice.name]: SwitchStateTypes;
  [miscSlice.name]: MiscState;
  [dappSlice.name]: IDappStoreState;
  [cmsSlice.name]: CMSState;
  [txFeeSlice.name]: TxFeeType;
  [imSlice.name]: IMStateType;
};
